### ISSUE TITLE
activestorage-ftp not on rubygems.org

### ISSUE THREAD

**Issue by fwolfst** [gordienko/activestorage-ftp#1]
The installation instructions will fail for the typical user, as `activestorage-ftp` is not published on rubygems.org .

To get rake tasks for uploading and releasing gems, I suggest using the Rakefile and gemspec that are generated when invoking `bundle new <gemname>` .

**Comment by gordienko** [comment]
Thank you, published on rubygems.org https://rubygems.org/gems/activestorage-ftp.
